---
# tasks file for ansible-role-nhc
#
 - name: configure NHC 
   template: src=nhc.conf.j2 dest=/etc/nhc/nhc.conf backup=yes mode=0644

 - name: add nhc scripts
   template: src={{ item }} dest=/etc/nhc/scripts/{{ item }} backup=yes mode=0644
   with_items: nhc_scripts
   when: nhc_scripts.0 != ""
