---
# tasks file for ansible-role-nhc

# - name: Check if lbnl-nhc-nhc_version is installed
#   package: pkg=lbnl-nhc-{{ nhc_version }} state=installed
#   register: reg_nhc_github_installed
#   check_mode: no
#   ignore_errors: True
#   when: nhc_github|bool

# - name: install NHC from github 
#   package: pkg={{ nhc_rpm_url }}
#   when: nhc_github|bool and reg_nhc_github_installed is failed

- name: install NHC from a yum repo
  ansible.builtin.package: 
    name: lbnl-nhc
    state: present
